# Generated by Django 5.0.4 on 2024-05-10 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snippet",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snippets",
                to="snippet.tag",
            ),
        ),
    ]
